### ISSUE TITLE
Question about org.elasql.remote.groupcomm.client.BatchSpcSender.BATCH_SIZE/MAX_WAITING_TIME

### ISSUE THREAD

**Issue by SuperDaYuanYuan** [elasql/elasql#69]
What do parameters org.elasql.remote.groupcomm.client.BatchSpcSender.BATCH_SIZE and org.elasql.remote.groupcomm.client.BatchSpcSender.MAX_WAITING_TIME stand for?

In Deterministic databases, transactions are executed in epochs that are always set to 10ms. In fact, some deterministic databases such as Aria use the number of transactions as the epoch size in their implementation.

So I wonder what is the relationship between org.elasql.remote.groupcomm.client.BatchSpcSender.BATCH_SIZE/MAX_WAITING_TIME and epoch size.

And where I can find the Variables or Parameters related to epoch size.

Thank you very much!

**Comment by SLMT** [comment]
Hi,

`org.elasql.remote.groupcomm.client.BatchSpcSender.BATCH_SIZE` simply stands for how many requests a client sends to the system at once in order to reduce communication overhead. After one of the servers receives those requests, it will directly hand over the requests as a batch to the communication module for total ordering among all servers.

`org.elasql.remote.groupcomm.client.BatchSpcSender.MAX_WAITING_TIME` stands for how much time a client can wait to send the next batch of transaction requests. It means that a client will send a batch of requests every `MAX_WAITING_TIME` milliseconds. This is close to the idea of the epoch times used in Calvin's paper [1]. However, if the size of the batch reaches `BATCH_SIZE` before the waiting time reaches `MAX_WAITING_TIME`, it will otherwise send the batch to the system no matter how much time left.

So, I think in our design our batches can be considered as epochs but divided by the number of transaction requests instead of time. To reach similar effect in Calvin's paper, you may have to set `BATCH_SIZE` to a large number and `MAX_WAITING_TIME` to the epoch time you want.

I hope this helps.

[1] Thomson, Alexander, et al. "Calvin: fast distributed transactions for partitioned database systems." Proceedings of the 2012 ACM SIGMOD International Conference on Management of Data. 2012.

**Comment by SuperDaYuanYuan** [comment]
Hi,

Thank you for your reply.

This helps me a lot! And I read your papers recently, and I think they are excellent!

Thanks again!
